[PROTOCOLS]
Virtual Screening = [
    {"tag": "section", "text": "PROTAC", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Ternary complex modeling", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtPROTACModel",   "text": "default"}
	    ]}
	]}
    ]
